### ISSUE TITLE
EAP7 on RHEL7

### ISSUE THREAD

**Issue by twm1010** [Maarc/ansible-role-redhat-jboss-eap#1]
After extraction: 
"msg": "Source /opt/jboss/jboss-eap-7.0/bin/init.d/jboss-as-standalone.sh not found"

It seems EAP7 service configuration is different?

**Comment by buuhsmead** [comment]
It is correct that you see this. You have skipped the creation of the Golden Image. Which is created through 'ansible_middleware_soe'. Inside that role there are scripts which do stuff. One of them is renaming jboss-eap-rhel.sh to jboss-as-standalone.sh. 
So if you want to use this role 'ansible-role-redhat-jboss-eap' you first have to create a GI (Golden Image) by role 'ansible_middleware_soe'.

**Comment by twm1010** [comment]
Thanks, make sense!
